/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_TestNative */

#ifndef _Included_jni_TestNative
#define _Included_jni_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_TestNative
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_TestNative_print
  (JNIEnv *, jobject);

/*
 * Class:     jni_TestNative
 * Method:    stringParam
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_TestNative_stringParam
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jni_TestNative
 * Method:    intParam
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jni_TestNative_intParam
  (JNIEnv *, jobject, jint);

/*
 * Class:     jni_TestNative
 * Method:    byteArrParam
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_TestNative_byteArrParam
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     jni_TestNative
 * Method:    setMethodString
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jni_TestNative_setMethodString
  (JNIEnv *, jobject);

/*
 * Class:     jni_TestNative
 * Method:    setMethodByteArray
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jni_TestNative_setMethodByteArray
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
